### ISSUE TITLE
🐛 Running workflow of nf-core framework in RDPC-QA got error

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo/workflow-roadmap#390]
## Describe the bug
The workflow in nf-core framework is running properly at local, while received exception when running in RDPC-QA.

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to 'https://wes.rdpc-qa.cancercollaboratory.org/runs'
2. Click on 'NEW RUN'
3. Input the following and submit RUN:
Workflow URL: https://github.com/icgc-argo-workflows/dnaalnqc
Workflow Params:
```
{
   "study_id":"TEST-QA",
   "analysis_ids":"0187b82f-1693-470a-87b8-2f1693f70ac9,4f6d6ddf-3759-4a30-ad6d-df37591a3033",
   "fasta":"/nfs-dev-1-vol-qa-1/reference/GRCh38_hla_decoy_ebv/GRCh38_hla_decoy_ebv.fa",
   "fasta_fai":"/nfs-dev-1-vol-qa-1/reference/GRCh38_hla_decoy_ebv/GRCh38_hla_decoy_ebv.fa.fai",
   "fasta_dict":"/nfs-dev-1-vol-qa-1/reference/GRCh38_hla_decoy_ebv/GRCh38_hla_decoy_ebv.dict",
   "germline_resource":"/nfs-dev-1-vol-qa-1/reference/gatk-resources/af-only-gnomad.pass-only.biallelic.snp.hg38.vcf.gz",
   "germline_resource_tbi":"/nfs-dev-1-vol-qa-1/reference/gatk-resources/af-only-gnomad.pass-only.biallelic.snp.hg38.vcf.gz.tbi",
   "song_url":"https://song.rdpc-qa.cancercollaboratory.org",
   "score_url":"https://score.rdpc-qa.cancercollaboratory.org"
}
```
Workflow Engine Params:
```
{
	"launchDir": "/nfs-dev-1-vol-qa-1/wfgn-launch",
	"projectDir": "/nfs-dev-1-vol-qa-1/wfgn-project",
	"revision": "main",
	"workDir": "/nfs-dev-1-vol-qa-1/wfgn-work"
}
```
4. received the following errors:
```
   {
      "message": "Exception while fetching data (/_entities) : null value in entry: multiqc_config=null",
      "path": [
        "_entities"
      ],
      "extensions": {
        "code": "DOWNSTREAM_SERVICE_ERROR",
        "serviceName": "song-search",
        "query": "query($representations:[_Any!]!){_entities(representations:$representations){...on Run{producedAnalyses{analysisId analysisType}inputAnalyses{analysisId analysisType analysisState files{name size}workflow{inputs workflowName workflowVersion}}}}}",
       "variables": {
          "representations": [
            {
              "__typename": "Run",
              "runId": "wes-59e3a240195f42e68e25bfcbede866fe",
              "parameters": {
                "analysis_ids": "0187b82f-1693-470a-87b8-2f1693f70ac9,4f6d6ddf-3759-4a30-ad6d-df37591a3033",
                "nucleotides_per_second": 200000,
                "api_token": "37a6259cc0c1dae299a7866489dff0bd",
                "plaintext_email": false,
                "monochrome_logs": false,
                "study_id": "TEST-QA",
                "verifybamid2_ud": "assets/verifybamid/1000g.phase3.100k.b38.vcf.gz.dat.UD",
                "max_cpus": 16,
                "multiqc_config": null,
                "score_container_version": "5.9.0",
                "max_multiqc_email_size": "25.MB",
                "hook_url": null,
                "max_time": "240.h",
                "target_interval": null,
                "germline_resource_tbi": "/nfs-dev-1-vol-qa-1/reference/gatk-resources/af-only-gnomad.pass-only.biallelic.snp.hg38.vcf.gz.tbi",
                "tracedir": null,
                "multiqc_logo": null,
                "validate_params": true,
                "multiqc_methods_description": null,
                "verifybamid2_mu": "assets/verifybamid/1000g.phase3.100k.b38.vcf.gz.dat.mu",
                "email_on_fail": null,
                "score_url": "https://score.rdpc-qa.cancercollaboratory.org",
                "score_container": "ghcr.io/overture-stack/score",
                "fasta_dict": "/nfs-dev-1-vol-qa-1/reference/GRCh38_hla_decoy_ebv/GRCh38_hla_decoy_ebv.dict",
                "fasta_fai": "/nfs-dev-1-vol-qa-1/reference/GRCh38_hla_decoy_ebv/GRCh38_hla_decoy_ebv.fa.fai",
                "version": false,
                "publish_dir_mode": "copy",
                "input": null,
                "score_url_download": null,
                "cleanup": false,
                "enable_conda": false,
                "verifybamid2_bed": "assets/verifybamid/1000g.phase3.100k.b38.vcf.gz.dat.bed",
                "transport_parallel": null,
                "local_mode": false,
                "aws_no_sign_request": false,
                "multiqc_title": null,
                "bait_interval": null,
                "score_url_upload": null,
                "song_url": "https://song.rdpc-qa.cancercollaboratory.org",
                "fasta": "/nfs-dev-1-vol-qa-1/reference/GRCh38_hla_decoy_ebv/GRCh38_hla_decoy_ebv.fa",
                "max_memory": "128.GB",
                "tempdir": null,
                "song_container": "ghcr.io/overture-stack/song-client",
                "email": null,
                "schema_ignore_params": "genomes",
                "transport_mem": null,
                "song_container_version": "5.0.2",
                "song_url_upload": null,
                "qc_analysis_ids": null,
                "no_intervals": false,
                "target": false,
                "outdir": null,
                "autosome_non_gap": "assets/autosomes_non_gap_regions.bed",
                "help": false,
                "show_hidden_params": false,
                "song_url_download": null,
                "skip_tools": "mosdepth,verifybamid2",
                "germline_resource": "/nfs-dev-1-vol-qa-1/reference/gatk-resources/af-only-gnomad.pass-only.biallelic.snp.hg38.vcf.gz",
                "reference_base": null
              }
            }
          ]
        },
        "classification": "DataFetchingException",
        "exception": {
          "stacktrace": [
            "GraphQLError: Exception while fetching data (/_entities) : null value in entry: multiqc_config=null",
            "    at downstreamServiceError (/appDir/node_modules/@apollo/gateway/dist/executeQueryPlan.js:268:12)",
            "    at /appDir/node_modules/@apollo/gateway/dist/executeQueryPlan.js:168:57",
            "    at Array.map (<anonymous>)",
            "    at sendOperation (/appDir/node_modules/@apollo/gateway/dist/executeQueryPlan.js:168:44)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
            "    at async executeFetch (/appDir/node_modules/@apollo/gateway/dist/executeQueryPlan.js:130:41)",
            "    at async executeNode (/appDir/node_modules/@apollo/gateway/dist/executeQueryPlan.js:82:17)",
            "    at async executeNode (/appDir/node_modules/@apollo/gateway/dist/executeQueryPlan.js:73:27)",
            "    at async executeNode (/appDir/node_modules/@apollo/gateway/dist/executeQueryPlan.js:56:40)"
          ]
        }
      }
    }
```

## Expected behaviour
The job can be kicked off and running successfully.

**Comment by bhavikbhagat93** [comment]
1. Need to reproduce on QA
2. propose solution 
3. fix

**Comment by lindaxiang** [comment]
Thanks @UmmulkiramR for investigating the issue. After further investigation, the job failed because of missing required reference files in rdpc-qa. 
However after staging the reference files, the job failed with the [same issue](https://github.com/icgc-argo/workflow-roadmap/issues/388) 
This issue can be closed for now.
